language: node_js   #设置语言
node_js: stable     #设置相应的版本
cache:
    directories:
        - node_modules    #据说可以减少travis构建时间
before_install:
  - npm install -g hexo
  - npm install -g hexo-cli
install:
  - npm install   #安装hexo及插件
before_script:
  - npm install -g mocha
  - git clone --branch master https://github.com/tangjiaqq/tangjiaqq.github.io.git
script:
  - hexo cl   #清除
  - hexo g   #生成
after_script:
  - ls
  only:
  - master  #只监测这个分支，一有动静就开始构建
env:
    global:
        - GH_REF: github.com/Longxr/Longxr.github.io.git